name: CI

on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - hardware/**
  push:
    branches:
    - master
    paths-ignore:
    - hardware/**

jobs:
  build:
    name: Run Tests
    runs-on: "${{ matrix.os }}"
    # runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        # python-version: ["3.7", "3.8", "3.9"]

    steps:

    - name: Check out the commit
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Select Python 3.7
      uses: actions/setup-python@v3
      with:
        # python-version: ${{ matrix.python-version }}
        python-version: "3.8"

    - name: Install PlatformIO
      run: |
        pip install -U -r tools/requirements.txt
        pio upgrade --dev
        pio pkg update --global

    - name: Run Builds
      run: |
        python make.py build sam --env all esp -v

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') && job.status == 'success' && github.ref == 'refs/heads/master'
      with:
        files: |
          bin/*


  clang_checks:
    name: Clang Format & Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the commit
        uses: actions/checkout@v3
        with:
          submodules: 'false'

      - name: Build clang checks Docker image
        run: docker build -t daphi-clang-checks guidelines_checks

      - name: Get changed files
        id: changed
        run: |
          git fetch --unshallow || true
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^esp/src/.*\.(cpp|h|ino)$' > changed-files.txt || true

      - name: Run clang-format (auto-format changed files)
        run: |
          if [ -s changed-files.txt ]; then
            docker run --rm -v "$PWD":/workspace -w /workspace daphi-clang-checks \
              sh -c 'clang-format -i $(cat changed-files.txt)'
          else
            echo "No changed source files to format."
          fi
              
      - name: Run clang-tidy checks on changed files
        run: |
          if [ -s changed-files.txt ]; then
            docker run --rm -v "$PWD":/workspace -w /workspace daphi-clang-checks \
              sh /workspace/guidelines_checks/run-clang-checks.sh $(cat changed-files.txt)
          else
            echo "No changed source files to check."
          fi
